[book]
authors = ["David Alejandro Mireles Llamas"]
language = "en"
multilingual = false
src = "src"
title = "Storage Mount Guardian"

[build]
build-dir = "public"
create-missing = false

[output.html]
default-theme = "rust"
preferred-dark-theme = "rust"
git-repository-url = "https://github.com/LOUST-PRO/storage-mountguardian"
edit-url-template = "https://github.com/LOUST-PRO/storage-mountguardian/edit/master/{path}"
additional-css = ["theme/custom.css"]
site-url = "/storage-mountguardian/"
no-section-label = false
mathjax-support = false
copy-fonts = true

[output.html.fold]
enable = true
level = 1

[output.html.playground]
editable = false
copyable = true
copy-js = true
line-numbers = true

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
